appName: user-profile-service
namespace: user-profile-dev
replicaCount: 1

image:
  repository: user-profile-service
  tag: "0.1.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30081

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"

serviceAccount:
  name: user-profile-sa
