apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
