appName: platform-demo-service
namespace: demo-dev
replicaCount: 1
image:
  repository: ghcr.io/frnxcode/platform-demo-service
  tag: "14da8a20f0904b324a3930c7f80185a6998f7e85"
  pullPolicy: IfNotPresent
service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30080
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"
serviceAccount:
  name: platform-demo-sa
