appName: platform-demo-service
namespace: demo-dev
replicaCount: 1
image:
  repository: 684779207098.dkr.ecr.eu-west-1.amazonaws.com/platform-demo-service
  tag: "a2e64e7e0056366320ccfd21d2396d423e2052df"
  pullPolicy: IfNotPresent
service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30080
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"
serviceAccount:
  name: platform-demo-sa
ingress:
  enabled: true
  host: demo.myinfracode.com
  certificateArn: arn:aws:acm:eu-west-1:684779207098:certificate/5754665b-8744-467c-9f97-16cd260cd1a3
