apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-profile-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/frnxcode/idp-mvp.git
    targetRevision: main
    path: services/user-profile-service/charts/user-profile-service
  destination:
    server: https://kubernetes.default.svc
    namespace: user-profile-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
